parameters:
#    event.example.class: Yoda\EventBundle\Example

services:
#    event.example:
#        class: %event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    security.access.event_voter:
      class:  Yoda\EventBundle\Security\Authorization\Voter\EventVoter
      public: false
      tags:
        - { name: security.voter }
