event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type:     annotation

login_check:
    path: /login_check

logout:
    path: /logout

